# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-30 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='类型名称')),
                ('desc', models.TextField(null=True, verbose_name='类型描述')),
                ('picture', models.ImageField(upload_to='static/upload/goodstype', verbose_name='类型图片')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
                'db_table': 'goodstype',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=20, verbose_name='聯絡方式')),
                ('upass', models.CharField(max_length=50, verbose_name='密碼')),
                ('uemail', models.EmailField(max_length=254, verbose_name='信箱')),
                ('uname', models.CharField(max_length=20, null=True, verbose_name='用戶名')),
                ('isActive', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '用戶',
                'verbose_name_plural': '用戶',
                'db_table': 'users',
            },
        ),
    ]
