# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-30 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=20, verbose_name='聯絡方式')),
                ('upass', models.CharField(max_length=50, verbose_name='密碼')),
                ('uemail', models.EmailField(max_length=254, verbose_name='信箱')),
                ('uname', models.CharField(max_length=20, null=True, verbose_name='用戶名')),
                ('isActive', models.BooleanField(default=True, verbose_name='啟用')),
            ],
        ),
    ]
